[package]
name = "libwinit-builder"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "builder"
path = "src/main.rs"

[dependencies]
shared-library-builder = { git = "https://github.com/feenkcom/shared-library-builder-rs" }
libwinit-library = { path = "../library" }