name: Cargo Build

on:
  push:
    branches:    
      - main

jobs:
    build:
        name: Build
        env:
            LIBRARY: Winit
        runs-on: ${{ matrix.variant.os }}
        strategy:
            matrix:
                variant:
                    - os: ubuntu-latest
                      prefix: lib
                      extension: .so
                      platform: linux
                    - os: macos-latest
                      prefix: lib
                      extension: .dylib
                      platform: osx
                    - os: windows-latest
                      prefix: ''
                      extension: .dll
                      platform: windows
        steps:
            - uses: actions/checkout@master
            - name: Install latest stable
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
            - name: Run cargo build
              uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release
              env:
                MACOSX_DEPLOYMENT_TARGET: 10.9
            - name: Deploy
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: target/release/${{matrix.variant.prefix}}${{env.LIBRARY}}${{matrix.variant.extension}}
                  remote: /var/www/html/${{env.LIBRARY}}/${{matrix.variant.platform}}/development/x86_64/lib${{env.LIBRARY}}${{matrix.variant.extension}}
                  host: ${{ secrets.FEENK_CLOUD }}
                  username: ubuntu
                  privateKey: ${{ secrets.SSH_KEY }}
